### ISSUE TITLE
Discord-Hybrid-Sharding

### ISSUE THREAD

**Issue by Huskydog9988** [shitcorp/Discord-Bots-At-Scale#16]
Seems like a worse version of Kurasuta, but also seems to be more maintained. maybe it should be considered a spiritual successor?

**Comment by meister03** [comment]
"Worse Version of Kurasuta" ?
Its the currently the working Version of if it. Kurasuta isn't maintained anymore and many users are reporting random crashes, bc the IPC Channel closes.

**Comment by Huskydog9988** [comment]
Edit: Ok so I'm an idiot and didn't think to go over your library again before commenting. I totally   missed the section where you can easily just plug-in your own discord.js client. So I apologize for this blatant misrepresentation of your library. Below is my original message.


Oh hey, wasn't expecting anyone, let alone a library dev to read this, but I guess I'll justify my point to you @meister03.

The reason I called your library a worse version was due to a lack of  customization that is present in Kurasuta. More specifically it  lacks support for custom discord.is clients. To me that is a key feature that can drastically improve performance with clients like discord.js-light.

**Comment by meister03** [comment]
It supports `discord.js-light` clients, I personally use it myself, the library does not require discord.js to work. It was built around it. Technically you could use any kind of  Discord Client, when they have the ready event.
