### ISSUE TITLE
Discord-Cross-Hosting

### ISSUE THREAD

**Issue by Huskydog9988** [shitcorp/Discord-Bots-At-Scale#17]
Great premise to scale existing discord.js bots, but should use redis or something else, not mongodb. Should also be more scalable, and not require the specifying of shards, machines, machine id, and preferable master. All should have been handled by the package, at least by default.

**Comment by meister03** [comment]
yeah, `mongodb` was a just a temporary solution. I am currently rewriting the whole package from scratch.
It now uses a `net-server`, where clients connects.
The net-server is used as a bridge.
**This is what we achieved:**
- Broadcastevals are 100% more faster (earlier: 114-2301ms, now: 7-20ms)
- Connection with Bot, Dashboard and other services are possible
- RollingRestart Option -> ShardData Updated -> respawn all Clusters/ add new clusters

In Plan:
- Machine Death -> Move Clusters to Machines, which are alive
- Load Balancing -> Respawn specific Clusters and spread the contained Internal Shard
- Auto Scaling -> Rolling Restart with newly added Shards

You might take a look at the package in https://github.com/meister03/discord-cross-hosting/tree/rewrite.

Now, you just have to provide the `totalMachines: ...` property. The `totalShards:` can be set to 'auto'.

The advantage is, that you connect all your services such as `dashboard, clusters....` -> e.g `request Guild_Data with the net-ipc...`

There are some new Features coming, I will send here a comment, when the package is ready for production.
